use crate::{
    report::{Finding, Recommendation, Report},
    severity::{Category, Severity},
};

const SNIPPET_CONTEXT_CHARS: usize = 90;
const MAX_SNIPPET_CHARS: usize = 260;
const MAX_ERRORS_SHOWN: usize = 15;

pub fn render_markdown(report: &Report) -> String {
    let mut lines = vec!["# Plugin Scan Report".to_string(), String::new()];
    push_header(&mut lines, report);
    push_verdict(&mut lines, report);

    if !report.capabilities.is_empty() {
        lines.push("## Capabilities".to_string());
        lines.push(String::new());
        for capability in &report.capabilities {
            lines.push(format!(
                "- **{}** ({}) — {}",
                capability.title,
                capability.severity.label(),
                capability.description
            ));
            if !capability.evidence.is_empty() {
                lines.push(format!("  - {}", code_list(&capability.evidence)));
            }
        }
        lines.push(String::new());
    }

    push_endpoints(&mut lines, report, 40);

    lines.push("## Findings".to_string());
    lines.push(String::new());
    if report.findings.is_empty() {
        lines.push("No findings.".to_string());
    }
    for severity in Severity::ALL_DESC {
        let findings: Vec<&Finding> = report
            .findings
            .iter()
            .filter(|finding| finding.severity == severity)
            .collect();
        if findings.is_empty() {
            continue;
        }
        lines.push(format!("### {} ({})", severity.label(), findings.len()));
        lines.push(String::new());
        for finding in findings {
            push_finding(&mut lines, report, finding, severity >= Severity::Medium);
        }
        lines.push(String::new());
    }

    push_files(&mut lines, report);
    push_errors(&mut lines, report);
    lines.join("\n")
}

/// Short disclosure meant for plugin pages and end users.
pub fn render_markdown_summary(report: &Report) -> String {
    let mut lines = vec!["# Plugin Security Summary".to_string(), String::new()];
    push_header(&mut lines, report);

    lines.push(match report.verdict.recommendation {
        Recommendation::Pass => {
            "No high-risk behaviour was found. The list below shows what the plugin can access."
                .to_string()
        }
        Recommendation::Review => {
            "This plugin uses powerful capabilities (listed below) that warrant a manual review."
                .to_string()
        }
        Recommendation::Block => "This plugin has issues that block publishing.".to_string(),
    });
    lines.push(String::new());

    let shown: Vec<_> = report
        .capabilities
        .iter()
        .filter(|capability| {
            !matches!(capability.category, Category::Archive | Category::Manifest)
                && capability.severity >= Severity::Low
        })
        .collect();
    lines.push("## What this plugin can do".to_string());
    lines.push(String::new());
    if shown.is_empty() {
        lines.push("Nothing beyond normal editor integration was detected.".to_string());
    }
    for capability in shown {
        lines.push(format!(
            "- **{}** — {}",
            capability.title, capability.description
        ));
        if !capability.evidence.is_empty() {
            lines.push(format!("  - {}", code_list(&capability.evidence)));
        }
    }
    lines.push(String::new());

    push_endpoints(&mut lines, report, 15);

    lines.push(
        "_Generated by an automated scanner. A capability is not proof of bad intent, and a clean scan is not a guarantee._"
            .to_string(),
    );
    lines.join("\n")
}

fn push_header(lines: &mut Vec<String>, report: &Report) {
    if let Some(plugin) = &report.plugin {
        lines.push(format!(
            "- **Plugin:** {} (`{}`) {}",
            plugin.name.as_deref().unwrap_or("Unknown"),
            plugin.id.as_deref().unwrap_or("unknown"),
            plugin.version.as_deref().unwrap_or("")
        ));
        if let Some(entry) = &plugin.entry {
            lines.push(format!("- **Entry script:** `{entry}`"));
        }
        if !plugin.permissions.is_empty() {
            lines.push(format!(
                "- **Declared permissions:** {}",
                code_list(&plugin.permissions)
            ));
        }
        if !plugin.dependencies.is_empty() {
            lines.push(format!(
                "- **Dependencies:** {}",
                code_list(&plugin.dependencies)
            ));
        }
    }
    lines.push(format!(
        "- **Analysed:** {} JS/HTML file(s), {} installed file(s), scanner {} / rules {}",
        report.stats.js_files_parsed,
        report.stats.installed_files,
        report.scanner_version,
        report.rules_version
    ));
    lines.push(String::new());
}

fn push_verdict(lines: &mut Vec<String>, report: &Report) {
    let verdict = &report.verdict;
    lines.push(format!(
        "**Recommendation: {}** · Risk: {} · Scan {}",
        recommendation_label(verdict.recommendation),
        verdict.risk.map_or("none", Severity::label),
        if verdict.complete {
            "complete"
        } else {
            "INCOMPLETE"
        }
    ));
    lines.push(String::new());
    if !verdict.reasons.is_empty() {
        lines.extend(verdict.reasons.iter().map(|reason| format!("- {reason}")));
        lines.push(String::new());
    }
}

fn push_endpoints(lines: &mut Vec<String>, report: &Report, limit: usize) {
    let endpoints: Vec<_> = report
        .endpoints
        .iter()
        .filter(|endpoint| !endpoint.tags.iter().any(|tag| tag == "local"))
        .collect();
    if endpoints.is_empty() {
        return;
    }
    lines.push("## Network hosts".to_string());
    lines.push(String::new());
    lines.push("| Host | Mentions | Notes |".to_string());
    lines.push("| --- | ---: | --- |".to_string());
    for endpoint in endpoints.iter().take(limit) {
        lines.push(format!(
            "| `{}` | {} | {} |",
            endpoint.host,
            endpoint.count,
            endpoint.tags.join(", ")
        ));
    }
    if endpoints.len() > limit {
        lines.push(format!("| … {} more | | |", endpoints.len() - limit));
    }
    lines.push(String::new());
}

fn push_finding(lines: &mut Vec<String>, report: &Report, finding: &Finding, with_snippet: bool) {
    let location = match (&finding.file, finding.span) {
        (Some(file), Some(span)) => format!("`{}:{}:{}`", file, span.start_line, span.start_column),
        (Some(file), None) => format!("`{file}`"),
        (None, _) => "`archive`".to_string(),
    };
    let count = if finding.occurrences > 1 {
        format!(" ×{}", finding.occurrences)
    } else {
        String::new()
    };
    lines.push(format!(
        "- `{}`{count} — {} ({}, {:?} confidence) at {location}",
        finding.id,
        finding.message,
        finding.category.key(),
        finding.confidence
    ));
    if !finding.evidence.is_empty() {
        lines.push(format!(
            "  - Evidence: `{}`",
            escape_backticks(&finding.evidence)
        ));
    }
    if !finding.examples.is_empty() {
        lines.push(format!("  - Also: {}", code_list(&finding.examples)));
    }
    if with_snippet && let Some(code) = snippet(report, finding) {
        lines.push(String::new());
        lines.push("  ```js".to_string());
        lines.push(format!("  {code}"));
        lines.push("  ```".to_string());
        lines.push(String::new());
    }
}

fn push_files(lines: &mut Vec<String>, report: &Report) {
    if report.files.is_empty() {
        return;
    }
    lines.push(format!("## Files ({})", report.files.len()));
    lines.push(String::new());
    lines.push("<details><summary>SHA-256 of installed files</summary>".to_string());
    lines.push(String::new());
    for file in &report.files {
        lines.push(format!(
            "- `{}` {} bytes, {} `{}`",
            file.path, file.size, file.kind, file.sha256
        ));
    }
    lines.push(String::new());
    lines.push("</details>".to_string());
    lines.push(String::new());
}

fn push_errors(lines: &mut Vec<String>, report: &Report) {
    if report.errors.is_empty() {
        return;
    }
    lines.push("## Scan errors".to_string());
    lines.push(String::new());
    for error in report.errors.iter().take(MAX_ERRORS_SHOWN) {
        lines.push(format!(
            "- `{}`: {}",
            error.file.as_deref().unwrap_or("scanner"),
            error.message
        ));
    }
    if report.errors.len() > MAX_ERRORS_SHOWN {
        lines.push(format!(
            "- … {} more",
            report.errors.len() - MAX_ERRORS_SHOWN
        ));
    }
}

pub fn recommendation_label(recommendation: Recommendation) -> &'static str {
    match recommendation {
        Recommendation::Pass => "Pass",
        Recommendation::Review => "Needs review",
        Recommendation::Block => "Block",
    }
}

fn snippet(report: &Report, finding: &Finding) -> Option<String> {
    let source = report.sources.get(finding.file.as_deref()?)?;
    let span = finding.span?;
    excerpt(source, span.start_byte, span.end_byte)
}

fn excerpt(source: &str, start: usize, end: usize) -> Option<String> {
    if source.is_empty() {
        return None;
    }
    let start = floor_boundary(source, start.min(source.len()));
    let end = ceil_boundary(source, end.min(source.len()).max(start));
    let line_start = source[..start].rfind('\n').map_or(0, |index| index + 1);
    let line_end = source[end..]
        .find('\n')
        .map_or(source.len(), |index| end + index);

    let from = back_chars(source, line_start, start, SNIPPET_CONTEXT_CHARS);
    let to = forward_chars(source, end, line_end, SNIPPET_CONTEXT_CHARS);
    let to = forward_chars(source, from, to, MAX_SNIPPET_CHARS);
    let prefix = if from > line_start { "…" } else { "" };
    let suffix = if to < line_end { "…" } else { "" };
    let text = source[from..to].trim();
    (!text.is_empty()).then(|| format!("{prefix}{text}{suffix}"))
}

fn floor_boundary(source: &str, mut index: usize) -> usize {
    while index > 0 && !source.is_char_boundary(index) {
        index -= 1;
    }
    index
}

fn ceil_boundary(source: &str, mut index: usize) -> usize {
    while index < source.len() && !source.is_char_boundary(index) {
        index += 1;
    }
    index
}

fn back_chars(source: &str, min: usize, index: usize, count: usize) -> usize {
    source[min..index]
        .char_indices()
        .rev()
        .nth(count.saturating_sub(1))
        .map_or(min, |(offset, _)| min + offset)
}

fn forward_chars(source: &str, index: usize, max: usize, count: usize) -> usize {
    source[index..max]
        .char_indices()
        .nth(count)
        .map_or(max, |(offset, _)| index + offset)
}

fn code_list(items: &[String]) -> String {
    items
        .iter()
        .map(|item| format!("`{}`", escape_backticks(item)))
        .collect::<Vec<_>>()
        .join(", ")
}

fn escape_backticks(value: &str) -> String {
    value.replace('`', "'")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn excerpt_handles_multibyte_and_long_lines() {
        let source = format!("{}é fetch('x') {}", "a".repeat(500), "b".repeat(500));
        let start = source.find("fetch").unwrap();
        let text = excerpt(&source, start, start + 5).unwrap();
        assert!(text.contains("fetch('x')"));
        assert!(text.starts_with('…') && text.ends_with('…'));
    }
}
